### ISSUE TITLE
cannot find module

### ISSUE THREAD

**Issue by zhang14725804** [yanyiwu/nodejieba#90]
cannot find module"..........\node_modules\_nodejieba@2.2.5@nodejieba/build/Release/nodejieba.node"

**Comment by bakabird** [comment]
feel sad,me too.

**Comment by yanyiwu** [comment]
试试用 nodejieba@2.2.4 的话有没有问题？

**Comment by zhang14725804** [comment]
不行

**Comment by yanyiwu** [comment]
@bakabird 你的报错信息能也贴一下吗？

**Comment by tw0517tw** [comment]
安裝的時候 node-gyp 沒有 build

**Comment by clfeng** [comment]
F:\code\file-4\mongoose-test\node_modules\pinyin>npm install
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@2.0.3: please upgrade to graceful-fs 4 for compatibility with current and future version                      s of Node.js

> nodejieba@2.2.5 install F:\code\file-4\mongoose-test\node_modules\pinyin\node_modules\nodejieba
> node-gyp rebuild


F:\code\file-4\mongoose-test\node_modules\pinyin\node_modules\nodejieba>if not defined npm_config_node_gyp (node "F:\Pro                      gram Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node                       "" rebuild )
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
F:\code\file-4\mongoose-test\node_modules\pinyin\node_modules\nodejieba\build\nodejieba.vcxproj(20,3): error MSB4019: 未
找到导入的项目“F:\Microsoft.Cpp.Default.props”。请确认 <Import> 声明中的路径正确，且磁盘上存在该文件。
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (F:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:2                      58:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "F:\\Program Files\\nodejs\\node.exe" "F:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node                      -gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd F:\code\file-4\mongoose-test\node_modules\pinyin\node_modules\nodejieba
gyp ERR! node -v v8.9.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: nodejieba@2.2.5 (node_modules\nodejieba):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: nodejieba@2.2.5 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

added 164 packages in 19.565s

F:\code\file-4\mongoose-test\node_modules\pinyin>npm install nodejieba

> nodejieba@2.2.5 install F:\code\file-4\mongoose-test\node_modules\pinyin\node_modules\nodejieba
> node-gyp rebuild
